### ISSUE TITLE
HTTP protocol

### ISSUE THREAD

**Issue by bromagosa** [edutec/Snap4Arduino-old-huge#13]
Just like in http://s4a.cat/#android under HTTP, it'd be swell to have an HTTP protocol for remote control.

**Comment by chrisclaynz** [comment]
I'm new to all this but currently trying to use VS1838b IR receiver to create a simple robot that I can control with a tv remote. Is this currently possible with snap4arduino? If so - how? If not - why and what might be the best workaround?

**Comment by edutec** [comment]
This issue was moved to edutec/Snap4Arduino#17
