### ISSUE TITLE
Show only the serial ports where an Arduino board is connected

### ISSUE THREAD

**Issue by bromagosa** [edutec/Snap4Arduino-old-huge#17]
At *s4aBlocks.js*, change this function:

    function(){ serialport.list(function (err, ports) { if(ports){ ports.forEach(function(each) { portList[each.comName] = each.comName })}})}

So that it filters out only the ports with an Arduino plugged in. It is pretty trivial to do, *each* serialport object has an attribute that can help with that (can't remember which one but it's easy to find out again).

**Comment by edutec** [comment]
This issue was moved to edutec/Snap4Arduino#14
