### ISSUE TITLE
SpriteMorph.prototype.arduino.showMessage should be refactored

### ISSUE THREAD

**Issue by bromagosa** [edutec/Snap4Arduino-old-huge#34]
showMessage doesn't belong here, this should be a GUI function.

Maybe we should also rename it into showModalMessage, and prevent any other action to happen while the box is up.

This would also prevent behaviour like clicking on connect and then on disconnect while the connection dialog is still open, thus helping on #32.

**Comment by edutec** [comment]
This issue was moved to edutec/Snap4Arduino#13
