### ISSUE TITLE
Communication problems with Arduino on MacOS when there are other bluetooth devices

### ISSUE THREAD

**Issue by maprzybylla** [edutec/Snap4Arduino-old-huge#39]
With the beta release I'm no longer able to connect my Arduino Uno to Snap4Arduino. I tried it with different Unos, using both the OldStandardFirmata and the current one. I can communicate with the Board in alpha version 1.0.6. and in Windows and also tested with the firmata_test program provided by firmata.org
![screen shot 2014-10-28 at 11 45 38](https://cloud.githubusercontent.com/assets/9349120/4808486/43e83d9c-5ea1-11e4-9e44-8c0ed138ca7d.png)
![screen shot 2014-10-28 at 11 45 59](https://cloud.githubusercontent.com/assets/9349120/4808482/38c4d308-5ea1-11e4-81b1-4871308c0f97.png)

**Comment by edutec** [comment]
This issue was moved to edutec/Snap4Arduino#9
