### ISSUE TITLE
Repository needs a roadmap to the top level

### ISSUE THREAD

**Issue by maueroats** [edutec/Snap4Arduino-old-huge#51]
This repository combines the source code from several other sources and includes huge binary blobs. You should clearly explain in the top level README what is going on. People expect to download and compile, but that's really not possible with the current setup.

**Comment by bromagosa** [comment]
You are 100% right.

I've been meaning to tidy things up for a long while... this repo should only include sources indeed, I'll try to make this a priority.

Thanks for your input!

**Comment by bromagosa** [comment]
Took me a while... but here's the new lightweight repo: https://github.com/edutec/Snap4Arduino
