### ISSUE TITLE
Reduce repository checkout size

### ISSUE THREAD

**Issue by mbanzi** [edutec/Snap4Arduino-old-huge#55]
the current repo is about 1gig and it's slow to check out. If you remove the binary release files and upload them somewhere else you'll make it easier for people to contribute.

nice project BTW

**Comment by bromagosa** [comment]
Indeed, I need to clean up... you're not the only one who's complained about this (#51).

I'll try to do it this week, promise!

**Comment by bromagosa** [comment]
"This week" was a really long one. Sorry!

Please check out the new lightweight repo: https://github.com/edutec/Snap4Arduino
