### ISSUE TITLE
what should be done to make the s4a support some basic functions of software serial?

### ISSUE THREAD

**Issue by Davis4Create** [edutec/Snap4Arduino-old-huge#70]
I would like to modify the s4a to make it support the functions of software serial, so that more serial ports could be used when Arduino UNO being connected. Can anyone gives me some instructions to achieve this?
Here is a tutorial about expansion, but I don't really think this is enough, the work might be more complex.
http://blog.s4a.cat/2015/03/13/Extending-Firmata-for-Snap4Arduino.html

Give my high appreciation to someone who may help!

**Comment by edutec** [comment]
This issue was moved to edutec/Snap4Arduino#4
