### ISSUE TITLE
Exporting as Arduino sketch should work the same as exporting projects

### ISSUE THREAD

**Issue by maprzybylla** [edutec/Snap4Arduino-old-huge#73]
It's very hard to see where the project was exported to, as the pop up window is only displayed for a second or so. Also, I'd like to choose the path myself :)

**Comment by bromagosa** [comment]
Duly noted. Will be releasing a new version next month, I'll do my best to include this along with several other improvements.

**Comment by edutec** [comment]
This issue was moved to edutec/Snap4Arduino#2
