### ISSUE TITLE
Cloud signup doesn't work

### ISSUE THREAD

**Issue by maprzybylla** [edutec/Snap4Arduino-old-huge#74]
When I try to sign up I get a message: 
"No such file - SnapCloudLocalSignUp.
An e-mail with your password has been sent to the address provided."
![errormsg](https://cloud.githubusercontent.com/assets/9349120/12477150/3a20d4d2-c02e-11e5-83cc-82af1ae30453.png)

**Comment by edutec** [comment]
This issue was moved to edutec/Snap4Arduino#1
